### ISSUE TITLE
Change of provider / playlist

### ISSUE THREAD

**Issue by NaseDC** [kiddac/XKlass#1]
It would be desirable if you could also change the individual providers in the main window.
e.g. cursor left/right

**Comment by kiddac** [comment]
It may be desirable, but it isn't that simple. There are lots of checks done on providers to see if they are active, banned, expired, disabled. Whether the playlists is in its max-connection limits etc. 
There is now an option to change the playlist on the main screen. This takes you to the screen that does all those checks.
