### ISSUE TITLE
Redirected to non-JSON content?

### ISSUE THREAD

**Issue by WanWizard** [kiddac/XKlass#2]
https://github.com/kiddac/XKlass/blob/69d2693ae17ec3d8ec706235e7ceab6fa077abcb/XKlass/usr/lib/enigma2/python/Plugins/Extensions/XKlass/vod.py#L391

I am gettting this error on a specific provider, but the header is present in the response when requesting the URL manually:
````
bash-5.1# uname -a
Linux sf8008 4.4.35 #1 SMP Mon Nov 6 17:52:38 UTC 2023 armv7l GNU/Linux
bash-5.1# wget --server-response -qO /dev/null "http://xxxx/player_api.php?username=xxxx&password=xxxx&action=get_live_streams"
  HTTP/1.1 200 OK
  Date: Thu, 18 Jul 2024 12:31:56 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Access-Control-Allow-Credentials: true
  Pragma: public
  Cache-Control: public, must-revalidate, proxy-revalidate
  CF-Cache-Status: DYNAMIC
  Report-To: xxx
  NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
  Server: cloudflare
  CF-RAY: 8a527dd79a167783-LHR
  alt-svc: h3=":443"; ma=86400
  ````

**Comment by WanWizard** [comment]
I've double-checked the response, it is valid json. The same playlist.txt works fine in xstreamity.

**Comment by kiddac** [comment]
okay I will amend the code next release. It was probably a bit of an overkill because of one provider who was showing a video when the account expired.
